title: PASW
description: Programming lab @ DIA, UniPR
google_analytics: 
show_downloads: true
theme: jekyll-theme-modernist

github:
  zip_url: https://github.com/tomamic/fondinfo/archive/master.zip
  tar_url: https://github.com/tomamic/fondinfo/archive/master.tar.gz

gems:
  - jekyll-mentions
